<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DTCDesk_Setup_Liviano</AssemblyName>
    <ApplicationIcon>..\DtcDesk.WinForms\logo-apk.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Payload.zip" />
  </ItemGroup>
</Project>
